# These are supported funding model platforms

github: [jetaimefrc, thaycacac]
patreon: demonslight
open_collective: vuejs
ko_fi: # Replace with a single Ko-fi username
tidelift: npm/vue
custom: # Replace with a single custom sponsorship URL